### ISSUE TITLE
refactor with the functor API

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/HistogramThresholding.jl#34]
After https://github.com/zygmuntszpak/ImageBinarization.jl/pull/70 the docstrings for `Yen` and others are missing. It's time for this package to switch to the functor API and re-organize the documentations.

By saying the functor API, we are speaking of the design of ImageBinarization and ImageContrastAdjustment, where the core algorithm is implemented in each type instead of the `find_threshold` function. An example of such API can be found in https://github.com/zygmuntszpak/ImageBinarization.jl/blob/86b7d593087c154a6ad86b76a95633df0305712b/src/algorithms/adaptive_threshold.jl#L107-L130

An example procedure of such refactor can be found in https://github.com/zygmuntszpak/ImageBinarization.jl/pull/29

**Comment by ashwani-rathee** [comment]
Hey @johnnychen94, from where I can start on this ??by writing HistogramThresholdingAPI.jl I think

**Comment by johnnychen94** [comment]
Hmmm, I would start with commenting out all the algorithms, and then rework the API one by one while still keeping the CI pass.

It would be helpful for us to review if you can only rework the API for one algorithm at a time only (especially for the first algorithm you're going to do)

**Comment by ashwani-rathee** [comment]
What I understood from your comment by doing a particular algorithm,I have to apply something similar to this: https://github.com/zygmuntszpak/ImageBinarization.jl/pull/32

**Comment by johnnychen94** [comment]
Correct, do notice that each PR is merged into `zygmuntszpak:api`  branch instead of `zygmuntszpak:master` branch.

The strategy I used there is to

1. first comment out all algorithms in https://github.com/zygmuntszpak/ImageBinarization.jl/pull/29
2. then for each algorithm, open a small PR, which will be merged into https://github.com/zygmuntszpak/ImageBinarization.jl/pull/29
3. merge https://github.com/zygmuntszpak/ImageBinarization.jl/pull/29 into master branch

The reasoning behind this is we still want to make sure `master` branch is a working version.

**Comment by zygmuntszpak** [comment]
Closed by #40
